// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID         int64
	UserID     int64
	DocumentID int64
	Title      string
	Text       string
	Embedding  pgvector.Vector
}

type Document struct {
	ID       int64
	UserID   int64
	Filename string
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
}
